# Generated by Django 3.0.4 on 2020-04-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=20, unique=True)),
                ('studentname', models.CharField(max_length=30)),
                ('studentgender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('studentform', models.CharField(choices=[('form1', 'FORM ONE'), ('form2', 'FORM TWO'), ('form3', 'FORM THREE')], max_length=5)),
                ('studentImage', models.ImageField(upload_to='static/images')),
                ('parentName', models.CharField(max_length=30)),
                ('parentContact', models.CharField(max_length=30)),
                ('parentLocation', models.CharField(max_length=30)),
                ('registrationDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
